# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

useCpp11 <- function() {
    .Call(`_toycpp11_useCpp11`)
}

myhypot <- function(x, y) {
    .Call(`_toycpp11_myhypot`, x, y)
}

rcpp_hello_world <- function() {
    .Call(`_toycpp11_rcpp_hello_world`)
}

